### PR TITLE
Update and rename Sponsorship_Opprotunities.md to Sponsorship_Opportu…

### PR DESCRIPTION
**Pull request by aackerman**
…nities.md

Fixes a simple typo

### CODE REVIEW

**Comment by randallmeeker** [comment]
Thanks. need to update the corresponding link on the website repo then will merge.

**Comment by brampersandon** [comment]
@randallmeeker Updated the build script in JavaScriptMN/javascriptmn.github.com@69f200f9df8723d8677e1b3b0f3990c89a5415d2

LGTM!

**Comment by aackerman** [comment]
@randallmeeker any issues with this?

**Comment by randallmeeker** [comment]
nope, sorry, thought i was blocked on something else. Looks good.

**Pull request merged**
